# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a62f66d2c81b95ed65497adb38414a236a265a539171c00a7886a461bfec3ac2950e19f77dafdc0296db30fbe8a40d4bc958af4468132a581b4742182a4f5821

test:
  secret_key_base: 3d539606c11d424f5ccb14fe1e522bd156b14c5706c6897f6efebc005e02a1e888125623b5dc266e7267cf525893458c2aad3614cc7b9f61a2b6c146061b38d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
